### PR TITLE
Added further parsing capabilities

### PR DESCRIPTION
**Pull request by ludwig-kastner**
Dear Mr. Völker,
thank you so much for open sourcing the FibexConverter tool.
With this PR I would like to contribute to the development of this tool by adding further parsing capabilities, mainly concerning frames and PDUs.
The code changes were tested with a single channel fibex.

Kind regards
Ludwig Kastner

### CODE REVIEW

**Comment by LarsVoelker** [comment]
I like it but it breaks the current code for all but configuration_to_text or certain FIBEX files.

I started to improve the code here: https://github.com/LarsVoelker/FibexConverter/tree/PR8-triage

**Comment by ludwig-kastner** [comment]
These changes are much more sophisticated than I anticipated with my small, little pull request. You're right, the changes break the other scripts, since the major program components run in the fibex_parser.py with the functions self.parse_pdus, self.parse_frames, etc and then the proposed changes need to be integrated into the other files aswell.

Looking at the fact that FlexRay allows for two channels, I was wondering if it would make sense to do exactly that, to split the channel parsing from the parsing of its respective content. Thus, I was wondering if it would make sense to integrate the self.parse_X functions in the configuration_to_X.py files directly?

**Comment by LarsVoelker** [comment]
I hope that I have fixed all the issues already.

Regarding FlexRay A vs B channel. I recognized that already and modified Interface, create_interface, and the FIBEX-Parsing already. Just have not tested with Channel B, since I have not found a FIBEX for that.

**Comment by ludwig-kastner** [comment]
So far the changes look really good and are really very user friendly and useable!
One more thing I would suggest is in configuration_to_text.py in line 843:
```
class PDUInstance(BasePDUInstance):
    def str(self, indent):
        if self.__pdu__ is not None:
            ret = indent * " "
            end_bit = self.__bit_position__ + 8 * self.__pdu__.byte_length() - 1
            ret += f"[Bit pos.: {self.__bit_position__}..{end_bit}] "
            ret += self.__pdu__.str(indent + 2, indent_first_line=False)
            return ret
        else:
            return ""
```
The reason for that is that in fibex_parser.py in line 415 the pdu attribute is optional, so if a PDU Instance has no associated PDU with it, the check for `self.__pdu__.byte_length()` would fail. With this suggestion, we could check if the PDU attribute is available, in case it is not the PDU Instance is printed as empty.

**Comment by LarsVoelker** [comment]
I am not sure that I understand. A PDU Instance must reference a PDU. So you are referring to the case that the FIBEX is not correct?

P.S. I think I see a bug in the fibex_parser.py around line 415, which I will fix.

**Comment by ludwig-kastner** [comment]
You are correct, the PDU Instance does indeed references a PDU. 
I looked deeper and the issue I described above when parsing the FIBEX I have available is rather that one Frame has a PDU Instance defined, that fails to reference a valid PDU, since the PDU it refers to isn't parsed, as the PDU has no signal-instances defined. The reason the PDU isn't parsed is the line 338 in fibex_parser.py `for pdu in root.findall('.//fx:PDUS/fx:PDU/fx:SIGNAL-INSTANCES/..', self.__ns__):`. As I said, this particular PDU has no signal-instances defined, thus it is not found there.
Sorry for the confusion there.

**Comment by LarsVoelker** [comment]
Ok, that makes sense now. I changed the code but I do not have an example file. So please check out the change.

**Comment by LarsVoelker** [comment]
I merged the changes.

**Pull request closed without merging**
